name: Run Setup Script

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  bitcoin-setup:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Check out the repository code

      - name: Run Bitcoin Core setup script
        run: |
          chmod +x .github/setup.sh
          .github/setup.sh

      - name: Start bitcoind in regtest mode
        run: |
          bitcoind -regtest -daemon
          echo "Waiting for bitcoind to be ready..."

          # Wait for bitcoind to start (max 30s)
          for i in {1..30}; do
            if bitcoin-cli -regtest getblockchaininfo > /dev/null 2>&1; then
              echo "bitcoind is ready!"
              break
            fi
            echo "Still waiting for bitcoind..."
            sleep 1
          done

      - name: Verify Bitcoin CLI version
        run: |
          BITCOIN_VERSION=$(submission/01.sh)
          echo "Bitcoin CLI Version: $BITCOIN_VERSION"

          if [[ $BITCOIN_VERSION == *"28"* ]]; then
            echo "Success: Bitcoin CLI version"
          else
            echo "Error: Bitcoin CLI version failed"
            exit 1
          fi

      - name: Verify Bitcoin chain
        run: |
            chmod +x submission/02.sh
            CHAIN=$(submission/02.sh)
            echo "Bitcoin chain: $CHAIN"
            if [[ "$CHAIN" == "regtest" ]]; then
              echo "Chain verification passed!"
            else
              echo "Chain verification failed!"
              exit 1
            fi
            